version: '3'
services:
## NODEJS
  wms-nodejs:
    image: izdock/nodejs-inde
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      #- ./config/nodejs/:/opt/inde/config/
      - ./data/nodejs/IDServer/appDirectory/apps:/opt/inde/IDServer/appDirectory/apps
    restart: always
    networks:
      wms-network:
        aliases:
          - nodejs
    stop_grace_period: 30s
    labels:
      it.initzero.description: "CloudWMS Application Server NodeJS"
      it.initzero.company: "InitZero S.r.l."
      it.initzero.component: "wms-nodejs"
